name: Automated API tests using Postman CLI

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
            distribution: 'zulu'
            java-version: '17'

      - name: Run database container
        run: |
          docker run --name signup6db -e POSTGRES_USER=signup4 -e POSTGRES_PASSWORD=s7p2+ -e POSTGRES_DB=signup -p 5432:5432 -d postgres:latest
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Start Spring Boot application
        run: java -Dspring.profiles.active=dev -jar build/libs/signup6-0.0.1-SNAPSHOT.jar &
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          postman collection run "21397567-0ea2e7e7-e725-46b9-ad77-3d5f9c61ba48"